### ISSUE TITLE
Layout: HTML and CSS

### ISSUE THREAD

**Issue by WitchDevelops** [commIT-Group/advice-generator-app#1]
- [x] Create the main container for the card
- [x] #6
- [x] #7
- [x] Add decorator line
- [x] Add the dice button
- [x] Add CSS variables for colors and fonts
- [x] #8
- [x] #9
- [x] #13

**Comment by anmolchhabra21** [comment]
Hi @WitchDevelops, I think I can help with these issues, please assign me any issue that is left open.

**Comment by car2t** [comment]
Hi all

The general layout is a pull request already.

If anyone needs help with the card layout let me know.

Let's do these people!!
