### ISSUE TITLE
Style footer

### ISSUE THREAD

**Issue by DevLoggith** [commIT-Group/Advice-generator-app#13]

**Comment by nikkehtine** [comment]
Idea: Add a background color to the footer, which will change to a random color after clicking on it. It could be a color from a list of predefined colors.

**Comment by WitchDevelops** [comment]
another idea:
design the footer in matching style to the main app (colors, fonts) BUT make some the letters in gradient. e.g. "commit group" can be in gradient. Like here: [example](https://pbs.twimg.com/media/Eck9EyDVAAAqJoh?format=png&name=4096x4096) ||[code hint](https://pbs.twimg.com/media/Eck9ZxoVAAA4pFX?format=png&name=medium)||
