### ISSUE TITLE
Write CSS for page layout (mobile/default styles)

### ISSUE THREAD

**Issue by caesiumtea** [commIT-Group/Advice-generator-app#22]
Part of #8 - write the CSS for sizing the page elements and arranging them on the page. Setting the colors for the different page regions can also be part of this.

This should be developed on the `feature/layout-mobile` branch.

**Comment by car2t** [comment]
Hi @caesiumtea  and all

I have sent a commit witch I think it will work for general layout.

Let me know what you all think.
