### ISSUE TITLE
Style text

### ISSUE THREAD

**Issue by caesiumtea** [commIT-Group/Advice-generator-app#23]
Part of #8 - write the CSS for styling the two text elements, to make them match the [style guide](https://github.com/commIT-Group/Advice-generator-app/blob/main/design/style-guide.md) and [preview images](https://github.com/commIT-Group/Advice-generator-app/tree/main/design) provided by Frontend Mentor. Partly done already.

This should be developed on the `feature/layout-mobile` branch.

**Comment by anmolchhabra21** [comment]
Hi @caesiumtea, I will be able to do this, please assign me this issue.

**Comment by caesiumtea** [comment]
@anmolchhabra21
I'm sorry, but we aren't looking for any new contributors. We're a group of friends just doing this project for practice. You can check the readme for a link to the project starter on Frontend Mentor if you want to try the same project yourself, and maybe you can find some other people to collaborate with in the Frontend Mentor community!

**Comment by WitchDevelops** [comment]
Did some of that [in here](https://github.com/commIT-Group/Advice-generator-app/pull/30/commits/4d618c455c99efb88ec85619e1b88fdcb2be28af)
