### ISSUE TITLE
Refreshing advice doesn't work on Firefox

### ISSUE THREAD

**Issue by nikkehtine** [commIT-Group/Advice-generator-app#28]
Testing on Edge, clicking the button or refreshing the page works as expected, and you get new advice from the API. However, that's not the case on Firefox, and you get new advice only when force refreshing the page with Ctrl+Shift+R.

- Firefox 111.0.1 (64bit)
- Windows 10 21H2 (64bit)

**Comment by nikkehtine** [comment]
Bing tells me this:

![obraz](https://user-images.githubusercontent.com/27138416/227555751-24167da6-8be5-4f08-b87b-9f615bb3fea4.png)

**Comment by car2t** [comment]
I imaging that was something like that but I did not know what exactly, so thank you for the explanation and your solution @nikkehtine.
Niice!

**Comment by car2t** [comment]
Hi all

I think is working fine now. Let me know.

**Comment by nikkehtine** [comment]
Thanks Carlos, I can confirm that it works now
