### ISSUE TITLE
Replace main repo README with updated README template from design folder

### ISSUE THREAD

**Issue by DevLoggith** [commIT-Group/advice-generator-app#3]

**Comment by nikkehtine** [comment]
I've updated the README in bad517fe8fb6ca922b2abe20ad520ee02ba63c9e in branch `feature/readme`. We will merge it later after building upon it when we're close to finishing the project. I think it's safe to close this issue.

**Comment by nikkehtine** [comment]
Linking #2 for tracking the readme file updates
