### ISSUE TITLE
Card width doesn't scale properly

### ISSUE THREAD

**Issue by nikkehtine** [commIT-Group/Advice-generator-app#37]
Current card width scaling doesn't feel natural

## Current screenshots

![1440px](https://user-images.githubusercontent.com/27138416/227797889-3180e611-ca4e-44c8-b1c4-f4e633f296ef.png)
**1440px**

![1439px](https://user-images.githubusercontent.com/27138416/227798197-55b4508c-6e47-48ac-8885-defff864fd9f.png)
**1439px**

![700px](https://user-images.githubusercontent.com/27138416/227798253-a4e297d0-8b6f-4e6a-86c9-cd43b81fa088.png)
**700px**

![699px](https://user-images.githubusercontent.com/27138416/227798466-0523c13b-e471-496f-88c1-e241a143357f.png)
**699px**

## The plan

Here is my rough solution to make it feel more natural. The numbers are just guesswork, they should be tested first to see if they work.

- **widescreen (default)**: fixed size, around 540px; `desktop` divider
- **5:8 ratio** - around 90%vw (viewport width); `mobile` divider

**If you have any suggestions, let me know in the discussion.**

I assigned myself this issue with the hopes of working on it soon, but if someone else wants to do it instead, I wouldn't mind handing it over (I'll be happy to help too).

I would also suggest not to close this issue after finishing the work on it, so that we can discuss together how we like the effect or what to change.

**Comment by car2t** [comment]
Hi @nikkehtine 

First, thank you for your time and ideas.

I think if we add something like this to our card, it will be enough for all devices:

```
#main-card {
  background-color: var(--n-blue-gray-dark);
  display: grid;
  /* more code for the grid here; grid-template: 4-rows */
  place-items: center;
  padding-top: 40px; /* Not necessary; the grid will do the job */
  width: 91.5vw; /* Not necessary; max-width and margin: 0 1rem; I think will work fine */
  height: 315px;
  box-sizing: content-box; 
  box-sizing: inherit; /* To be sure our box size will be till the border, no content. */
  max-width: whatever;
  margin: 0 1rem; /* In mobile will leave some margin at both sides */
}
```
With something like that we could delete the media query too; witch is making our card visualy "jump" right now.

What do you think?

**Comment by car2t** [comment]
Hi again @nikkehtine 

I think after merge my last pull request, still going, it will work better then we can fix the card layout too.

Happy coding!!

**Comment by car2t** [comment]
Hi @nikkehtine 

Check the web app now. I have merged the branch already.

What you think?
