### ISSUE TITLE
Use `<meta charset="utf-8">` instead of `"Content-type"`

### ISSUE THREAD

**Issue by nikkehtine** [commIT-Group/advice-generator-app#46]
Suggestion by Webhint extension:

![image](https://user-images.githubusercontent.com/27138416/232496282-83c70a5f-7b1e-4bb6-9829-ba6c6d31e769.png)

This change was made to try and fix #38, which it didn't, so I suppose we could roll it back to the recommended practice.

Let me know what you think.

**Comment by car2t** [comment]
Yep, just do it.
I forgot that one.

**Comment by WitchDevelops** [comment]
yes, if it didn't fix the issue then roll it back.
