### ISSUE TITLE
Create desktop layout: add media queries to the main div (CSS)

### ISSUE THREAD

**Issue by WitchDevelops** [commIT-Group/Advice-generator-app#9]

**Comment by anmolchhabra21** [comment]
Hi @WitchDevelops, I think I can help with these, can I work on these issues?

**Comment by WitchDevelops** [comment]
Sorry, we aren't looking for external contributors :) We're agroup of friends trying to learn some proper GitHub workflow, coding itself is not the goal here. Maybe we could collaborate in the future :)

**Comment by car2t** [comment]
Hi @WitchDevelops 

Do you think we can close this issue too after merge _mobile-layout_ branch?
